version: "3.7"

services:
  portainer_agent:
    image: portainer/agent
    container_name: portainer_agent
    restart: always
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock 
        - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - 9001:9001

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: always
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ./nginx-proxy-manager/data:/data
      - ./letsencrypt:/etc/letsencrypt

volumes:
  nginx-proxy-manager:

networks:
  default:
    external:
      name: nginx-proxy
