version: '3'

services:
  spark-master:
    image: docker.io/bitnami/spark:3.3
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8282:8080'
    volumes:
      - "/root/spark/data:/data-import:rw"
    networks:
      - nginx-proxy
      - spark
      
  spark-worker-1:
    image: docker.io/bitnami/spark:3.3
    container_name: spark-worker-1
    depends_on:
      - spark-master
    networks:
      - spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no

networks:
  nginx-proxy:
    name: nginx-proxy
    external: true
  spark:
    name: spark
    external: true
